### ISSUE TITLE
the function listlen

### ISSUE THREAD

**Issue by pobin6** [fbb-git/yodl#3]
I build the yodl failed.
The reason is that I can find the function listlen.
I see the icmake direction,surely, I can't find it.
why did you use the function?

**Comment by fbb-git** [comment]
Dear Hideman, you wrote:
> I build the yodl failed.
> The reason is that I can find the function listlen.
> I see the icmake direction,surely, I can't find it.
> why did you use the function?

Thank you for your e-mail about Yodl. To answer your question: the function
listlen is used to return the length of an icmake list variable (see icmake's
man-page. 

There is no function listlen in Yodl, but icmake certainly has a function
listlen. Using icmake's current version (9.02.02) a simple icmake script like

    void main(int argc, list argv)
    {
        printf("length: ", listlen(argv), "\n");
    }
    
shows 
    
    demo: 1

-- 
    Frank B. Brokken
    Center for Information Technology, University of Groningen
    (+31) 50 363 9281 
    Public PGP key: http://pgp.surfnet.nl
    Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA

**Comment by pobin6** [comment]
OK, I may build the icmake worry.
Thanks for your answer.

**Comment by fbb-git** [comment]
Since there's no further action required I now close this issue.
